### ISSUE TITLE
jumpscripts are not synced correctly to agents

### ISSUE THREAD

**Issue by Hamdy** [Jumpscale/agentcontroller2#13]
Scenario:
- Creating Master Vmachine with agentcontroller2
- Creating several Vmachines with agents and registered to agentcontroller2

Problem:
jumpscripts are not synced to agents.
I have to restart agentcontroller2 in order for those to be picked

**Comment by muhamadazmy** [comment]
@despiegk We didn't manage to reproduce this issue on dev env or the affected env. The only thing that I think can causes this is a timeout in the startup script due to slow agent machine. But even in such situation I couldn't reproduce. 

Note the following:
- Startup script assumes a timeout of 30 seconds
- Agent extension script retries if it failed to contact syncthing up to 3 times. It waits 5, 10, and 15 seconds before each trial.

Note, a time out error in the start script will print an error in the agentcontroller2 logs.I checked  the logs on @Hamdy env and didn't find any errors (but he had a very busy env and the error might just gone undetected)
