### ISSUE TITLE
Package naming: a "client" and a "newclient" package?

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/agentcontroller2#15]

**Comment by amrhassan** [comment]
`client` is a low-level client that @muhamadazmy wrote initially and `newclient` is a another client implementation that I wrote later with high-level operations described in the API for the convenience of the user. I used it to build [agentcontroller2-webclient](https://github.com/Jumpscale/agentcontroller2-webclient/). (see [README](https://github.com/Jumpscale/agentcontroller2/tree/master/newclient) for more details about that)

I temporarily named it `newclient` until we discuss if we're keeping both clients or updating all code to use `newclient` since it can do low-level command sending and response receiving as well.

**Comment by amrhassan** [comment]
@robvanmieghem Do you have any code using `client` other than the scenario tests from `agent2`?

**Comment by robvanmieghem** [comment]
@amrhassan Safekeeper is, but this can be refactored.

**Comment by amrhassan** [comment]
`newclient` will become `client` once Safekeeper is updated to use `newclient`.

**Comment by robvanmieghem** [comment]
Just refactor it now, safekeeper will follow.
