### ISSUE TITLE
create easy python client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/agentcontroller2#5]
specs on 
https://github.com/Jumpscale/docs/blob/master/MultiNode/AgentController2/EasyClient.md

**Comment by robvanmieghem** [comment]
* In the implementation it is `j.clients.ac.get` instead of  `j.ac.get` as in the spec
* Provide docstrings on [SimpleClient](https://github.com/Jumpscale/jumpscale_core7/blob/master/lib/JumpScale/lib/agentcontroller2client/simple.py#L128) to provide some help in the jshell
* I find Fanout a confusing name, also the default should be true, not false

**Comment by robvanmieghem** [comment]
* sync and portforward not implemented on the simple client apparently

**Comment by muhamadazmy** [comment]
Yes, I am still working on those.
